name: Language-MzScheme
version: 0.01
abstract: Perl bindings to PLT MzScheme
author: Autrijus Tang <autrijus@autrijus.org>
license: perl
distribution_type: module
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.33
